#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/Users/frankmazza/opt/anaconda2/envs/lfpy"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/Users/frankmazza/opt/anaconda2/envs/lfpy/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/Users/frankmazza/Desktop/LFPy-Frank/L5bPCmodelsEH/mod/x86_64/.libs/libnrnmech.so" "$@"
